### ISSUE TITLE
v0.3.x compatibility?

### ISSUE THREAD

**Issue by terinjokes** [BinaryMuse/toml-node#15]
[v0.3.x](https://github.com/toml-lang/toml/releases/tag/v0.3.0) adds support for:

* Add scientific notation for floats.
* Allow optional + prefix on integers.
* Switch to RFC 3339 for datetimes (allowing offsets and fractional seconds).
* Add multiline and literal strings.

**Comment by BinaryMuse** [comment]
v2.1.1 is published with support for the 0.3.1 spec
