### ISSUE TITLE
0.4.0 Spec

### ISSUE THREAD

**Issue by futagoza** [BinaryMuse/toml-node#18]
Just thought Id'e tell you, the 0.4.X Spec is out

**Comment by mojombo** [comment]
I came to say the same thing! I'd love to move toml-node to the v0.4.0-compliant section of the TOML spec once you have a chance to update it.

https://github.com/toml-lang/toml#v040-compliant

Changelog is here:

https://github.com/toml-lang/toml/releases/tag/v0.4.0

Awesome work!

**Comment by BinaryMuse** [comment]
Thanks to both of you, it's definitely on the list (the list is just long :)

**Comment by mojombo** [comment]
Cool!

**Comment by BinaryMuse** [comment]
Closed by v2.2.0
