### ISSUE TITLE
PEG doesn't handle quoted key names per spec

### ISSUE THREAD

**Issue by othiym23** [BinaryMuse/toml-node#21]
I'm sorry I keep coming up with these picayune edge cases, but these are all things I'm trying to handle in my TOML output stream, and the rules for TOML are considerably stricter than JSON in some ways, so I'm coming up with a bunch of output I can't round-trip through `toml`.

It's also possible that my reading of the spec is incorrect, although I think the way it deals with the quoted key with the dot in it is just wrong.

```javascript
toml.parse('["the\\ key"]\n\none = "one"\ntwo = 2\nthree = false')
// => SyntaxError: Expected "]" but " " found.
toml.parse('[a."the\\ key"]\n\none = "one"\ntwo = 2\nthree = false')
// => SyntaxError: Expected "]" but " " found.
toml.parse('[a."the-key"]\n\none = "one"\ntwo = 2\nthree = false')
{ a: { '"the-key"': { one: 'one', two: 2, three: false } } }
toml.parse('[a."the.key"]\n\none = "one"\ntwo = 2\nthree = false')
{ a: { '"the': { 'key"': [Object] } } }
```

**Comment by BinaryMuse** [comment]
Sorry for the long delay on this. I've added support plus [several test cases](https://github.com/BinaryMuse/toml-node/commit/de73efbd48ee68294177fe92b37e200050263b47#diff-a05be9580bdc3f11fe3d9723c8433808R371) (including the ones above). It should be good to go in v2.3.0, released today.
