### ISSUE TITLE
Parsing error in unquoted section names

### ISSUE THREAD

**Issue by h2non** [BinaryMuse/toml-node#26]
This issue was introduced in `v2.3.0`.

In previous versions the following is parsed properly:
```toml
[/sample]
key = "value"
```
But now the `pegjs` parser throws the following:
```
throw peg$buildException(null, peg$maxFailExpected, peg$maxFailPos);
            ^
SyntaxError: Expected "[", "\"", [ \t] or [A-Za-z0-9_\-] but "/" found.
```

TOML spec didn't change, so this is a parser error, probably due to this changes (both quoted and unquoted expressions must be supported):
https://github.com/BinaryMuse/toml-node/commit/de73efbd48ee68294177fe92b37e200050263b47#diff-43f9e8cc9f4030c620a395ebeded25e1R83

**Comment by BinaryMuse** [comment]
Bare keys cannot contain `/`. The changes in 2.3.0 brought the parser more in line with the spec. I apologize for the confusion.

From [the spec](https://github.com/toml-lang/toml#table):

> Keys may be either bare or quoted. **Bare keys** may only contain letters,
numbers, underscores, and dashes (`A-Za-z0-9_-`). Note that bare keys are
allowed to be composed of only digits, e.g. `1234`. **Quoted keys** follow the
exact same rules as basic strings and allow you to use a much broader set of key
names. Best practice is to use bare keys except when absolutely necessary.

**Comment by h2non** [comment]
I see. Curiously other TOML parsers I've used seems like doesn't follow the spec strictly.

**Comment by BinaryMuse** [comment]
Someone mentioned in a comment somewhere that quoted keys were a newer addition.
