### ISSUE TITLE
toml-node don't accept single quoted key

### ISSUE THREAD

**Issue by bungcip** [BinaryMuse/toml-node#34]
```
'key2' = "value"
```
produce error  
```
Error at line 1 column 1:
Expected "#", "[", "\"", "\n", "\r", [ \t], [A-Za-z0-9_\-] or end of input but "'" found.
```

which is valid input according TOML Spec 
(https://github.com/toml-lang/toml#user-content-keyvalue-pair).

**Comment by BinaryMuse** [comment]
Thanks for the report! This is fixed in v2.3.2.
