### ISSUE TITLE
[Feature request] Generating toml from json?

### ISSUE THREAD

**Issue by kkimdev** [BinaryMuse/toml-node#38]

**Comment by jmeischner** [comment]
+1

**Comment by gramakri** [comment]
Isn't this just JSON.stringify(toml.parse(someTomlString)) ?

**Comment by kkimdev** [comment]
Sorry for the mistake, updated the title :)

**Comment by gramakri** [comment]
I was looking exactly for this as well :-) For now, I am trying out https://github.com/jakwings/tomlify-j0.4

**Comment by tech4him1** [comment]
@kkimdev I believe this is a duplicate of #27.

**Comment by kkimdev** [comment]
@tech4him1 right, thanks!
