### ISSUE TITLE
Toml should not add a key which is protected or private

### ISSUE THREAD

**Issue by supanadit** [BinaryMuse/toml-node#57]
![test1](https://user-images.githubusercontent.com/33617149/64072422-264add00-ccb8-11e9-8360-c4dd1d3db64a.png)
![test2](https://user-images.githubusercontent.com/33617149/64072423-2a76fa80-ccb8-11e9-824f-99125908c824.png)

I am using typescript, it should not appear on TOML after parse if the variable was Protected or Private

**Comment by lazarljubenovic** [comment]
The information about protected/private isd not available at runtime. TypeScript only uses the class member modifiers to statically analyze your code at compile-time. After compilation is done, a private attribute on a class is no different than a public one.

**Comment by supanadit** [comment]
So it is impossible to hide unwanted key while parsing to TOML ?

**Comment by lazarljubenovic** [comment]
It doesn't have much to do with TOML, the exact same thing would happen if you'd want to serialize to JSON. Unless, of course, you're using static analysis to read the code (as opposed to execute the code in the browser or in Node environment).

To do it at run-time, you might want to check our decorators. For example, [`class-transformer`](https://github.com/typestack/class-transformer) utilizes them to perform serialization for sending and receiving data via the network.
